### ISSUE TITLE
images_and_labels.npy and pre_images.npy files

### ISSUE THREAD

**Issue by abderhasan** [cosmicac/ucsf-mri-seg#1]
Hello,

In your README file you mention `images_and_labels.npy` and `pre_images.npy`, but couldn't find them in your code. Will they be created by some means or you just forgot to include them?

Thanks.

**Comment by cosmicac** [comment]
Unfortunately, I realized later that I could not include them since they contain sensitive patient data. I could tell you the dimensions/format that they are expected to be in - would that help you?

**Comment by abderhasan** [comment]
Thanks so much, that's totally fine. Sure, if you have some sample file for instance that would show the structure of the data, that would be very helpful indeed.

**Comment by cosmicac** [comment]
#### Here's how you would generate sample data that has the same structure:

```
import numpy as np

# Sample size. Could be anything.
SAMPLE_SIZE = 10

images_and_labels = np.zeros((SAMPLE_SIZE, 2, 512, 512, 20))
pre_images = np.zeros((SAMPLE_SIZE, 512, 512, 20))

# Save to disk, if you want.
np.save('images_and_labels', images_and_labels)
np.save('pre_images', pre_images)
```

#### Here's the explanation of the dimensions for `images_and_labels`:

`SAMPLE_SIZE`: This is just the number of MRI sample images you have. 

`2`: this dimension indexes the images versus the labels (i.e. `images_and_labels[:,0,:,:,:]` returns the images, `images_and_labels[:,1,:,:,:]` returns the labels)

`512 x 512 x 20`: These are the dimensions of a single image.

#### Here's the explanation of the dimensions for `pre_images`:

`pre_images` is just another sequence of images - (another "channel" of data).

`SAMPLE_SIZE`: This is just the number of MRI sample images you have. 

`512 x 512 x 20`: These are the dimensions of a single image.

**Comment by abderhasan** [comment]
Looks great! Thanks so much for your kind support.
